stages:
  - build
  - publish

variables:
  production_repo: services.ub.uni-leipzig.de:11443/bdd_dev/dev-dotdeb

docker_build:
  stage: build
  image: ubleipzig/deployer:1.2.4
  services:
    - docker:18.09-dind
  script: |
    deployer build \
      --build-arg HTTP_PROXY="${HTTP_PROXY}" \
      --build-arg FTP_PROXY="${FTP_PROXY}" \
      --build-arg HTTPS_PROXY="${HTTPS_PROXY}" \
      --build-arg NO_PROXY="${NO_PROXY}" \
      --output image.tar.gz
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - image.tar.gz
  artifacts:
    name: docker-image
    paths:
      - image.tar.gz
  tags:
    - docker

docker_publish_production:
  stage: publish
  image: ubleipzig/deployer:1.2.4
  services:
    - docker:18.09-dind
  script: |
    declare version=`expr ${CI_COMMIT_TAG} ':' 'php/\(.\+\)'`
    declare major_version=`expr ${version} ':' '\([^.]\+\)'`
    declare minor_version=`expr ${version} ':' '[^.]\+\.\([^.]\+\)'`
    declare patch_version=`expr ${version} ':' '[^.]\+\.[^.]\+\-\(.\+\)'`

    deployer publish \
      --input image.tar.gz \
      --docker-config "${DOCKER_PRODUCTION_AUTH_CONFIG}" \
      --name ${production_repo} \
      --tag latest \
      --tag ${version} \
      --tag "${major_version}.${minor_version}" \
      --tag "${major_version}"
  dependencies:
    - docker_build
  tags:
    - docker
  only:
    - /^php\/.*/