stages:
  - build
  - publish

variables:
  production_repo: ubleipzig/dev-dotdeb

dev-dotdeb_build:
  stage: build
  image: ubleipzig/deployer:1.3.2
  services:
    - docker:dind:18.09-dind
  script: |
    deployer build \
      --build-arg HTTP_PROXY="${HTTP_PROXY}" \
      --build-arg FTP_PROXY="${FTP_PROXY}" \
      --build-arg HTTPS_PROXY="${HTTPS_PROXY}" \
      --build-arg NO_PROXY="${NO_PROXY}" \
      --output image.tar.gz
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - image.tar.gz
  artifacts:
    name: docker-image
    paths:
      - image.tar.gz
  tags:
    - docker

dev-dotdeb_publish:
  stage: publish
  image: ubleipzig/deployer:1.3.2
  services:
    - docker:dind
  script: |
    export version=`expr ${CI_COMMIT_TAG} ':' 'php/\(.\+\)'`
    export major_version=`expr ${version} ':' '\([^.]\+\)'`
    export minor_version=`expr ${version} ':' '[^.]\+\.\([^.]\+\)'`
    export patch_version=`expr ${version} ':' '[^.]\+\.[^.]\+\-\(.\+\)'`

    deployer publish \
      --input image.tar.gz \
      --docker-config "${DOCKER_PRODUCTION_AUTH_CONFIG}" \
      --name ${production_repo} \
      --tag latest \
      --tag ${version} \
      --tag "${major_version}.${minor_version}" \
      --tag "${major_version}"
  dependencies:
    - docker_build
  tags:
    - docker
  only:
    - /^php\/.*/