stages:
  - image
  - mirror

dev-dotdeb_image:
  stage: image
  image: docker:latest
  services:
    - docker:18.09-dind
  script: |
    test "${DOCKER_PRODUCTION_AUTH_CONFIG}" == "" && echo "docker-config does not exists, aborting!" && false
    mkdir -p ~/.docker && echo "$DOCKER_PRODUCTION_AUTH_CONFIG" >~/.docker/config.json
    export version=`expr ${CI_COMMIT_TAG} ':' 'php\([^-]\+\)'`
    export major_version=`expr ${version} ':' '\([^.]\+\)'`
    export minor_version=`expr ${version} ':' '[^.]\+\.\([^-]\+\)'`
    export suffix=`expr ${CI_COMMIT_TAG} ':' '[^-]\+-\(.*\)'`
    docker build --pull -t ubleipzig/dev-dotdeb:${version}-${suffix} -f ${version}/Dockerfile .
    docker push ubleipzig/dev-dotdeb:${version}-${suffix}
    for tag in "latest" "${major_version}" "${version}"; do
      docker tag  ubleipzig/dev-dotdeb:${version}-${suffix} ubleipzig/dev-dotdeb:${tag}
      docker push ubleipzig/dev-dotdeb:${tag}
    done
  tags:
    - docker
  only:
    - /^php\/.*/

github_mirror:
  stage: mirror
  image:
    name: alpine/git
    entrypoint: [ "/bin/sh", "-c" ]
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script: |
    cd /tmp
    git clone --mirror ${CI_REPOSITORY_URL} project
    cd project
    git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/ubleipzig/ubleipzig/dev-dotdeb.git
    git push --mirror github
  tags:
    - docker
