#!/bin/bash

set -e

cat >/etc/apache2/mods-available/fcgid.conf <<EOF
<IfModule mod_fcgid.c>
	FcgidConnectTimeout 20
	<FilesMatch \.(php|php5)\$>
		AddHandler fcgid-script .php .php5
	</FilesMatch>
	SocketPath /var/lib/apache2/fcgid/sock
	IdleTimeout 3600
	IdleScanInterval 120
	BusyTimeout 300
	BusyScanInterval 120
	ErrorScanInterval 3
	ZombieScanInterval 3
	ProcessLifeTime 30
	SpawnScoreUpLimit 10
	SpawnScore 1
	TerminationScore 2
	MaxProcessCount 5
	DefaultMaxClassProcessCount 2
	DefaultMinClassProcessCount 1
	IPCConnectTimeout 3600
	IPCCommTimeout 3600
	MaxRequestsPerProcess 20
	Passheader AUTHORIZATION
	FcgidMaxRequestLen ${FCGID_MAX_REQUEST_LEN}
	<Directory "/var/www/fcgid/">
		AllowOverride None
		Options +ExecCGI +MultiViews -Indexes
		Order allow,deny
		Allow from all
	</Directory>
</IfModule>
EOF

cat >/etc/apache2/sites-available/99-app.conf <<EOF
Alias / ${APP_HOME}/
<IfModule suexec_module>
	SuexecUserGroup ${APP_USER} ${APP_USER}
</IfModule>

<Directory ${APP_HOME}>
	FCGIWrapper /var/www/fcgid/php-fcgi .php
	Options +ExecCGI
	AllowOverride All
	Require all granted
</Directory>
EOF

sed -e 's!^\(\s*ErrorLog\s\+\).*$!\1 /dev/stderr!' -i /etc/apache2/apache2.conf /etc/apache2/sites-available/*
sed -e 's!^\(\s*CustomLog\s\+\).*$!\1 /dev/stdout combined!' -i /etc/apache2/apache2.conf /etc/apache2/sites-available/*


a2enmod ssl rewrite suexec fcgid shib2
a2ensite 99-app default-ssl
a2disconf other-vhosts-access-log

# configure supervisord to start apache2
cat >/etc/supervisor/conf.d/apache2.conf <<EOF
[program:apache2]
priority = 10
environment = HOME="/var/www",APACHE_LOCK_DIR="/var/lock/apache2",APACHE_PID_FILE="/var/run/apache2.pid",APACHE_RUN_USER="www-data",APACHE_RUN_GROUP="www-data",APACHE_RUN_DIR="/var/run/apache2"
command = /usr/sbin/apache2 -DFOREGROUND
user = root
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = ${LOG_DIR}/supervisor/supervisord.log
EOF
