#!/bin/bash

set -e

cat >/etc/apache2/sites-available/99-app.conf <<EOF
Alias / ${APP_HOME}/
<Directory ${APP_HOME}>
	Require all granted
	Options Indexes FollowSymLinks
	IndexOptions FancyIndexing
	AllowOverride All
</Directory>
EOF

sed -e 's!^\(\s*ErrorLog\)\s\+.*$!\1 /dev/stderr!' -i /etc/apache2/apache2.conf /etc/apache2/sites-available/*
sed -e 's!^\(\s*CustomLog\)\s\+.*$!\1 /dev/stdout combined!' -i /etc/apache2/apache2.conf /etc/apache2/sites-available/*
sed -e 's!^\(\s*Timeout\)\s\+.*$!\1 3600!' -i /etc/apache2/apache2.conf /etc/apache2/sites-available/*

a2enmod ssl rewrite proxy_fcgi shib2 setenvif
a2ensite 99-app default-ssl
a2disconf other-vhosts-access-log

test -e /var/run/apache2.pid && rm /var/run/apache2.pid

# configure supervisord to start apache2
cat >/etc/supervisor/conf.d/apache2.conf <<EOF
[program:apache2]
priority = 10
environment = HOME="/var/www",APACHE_LOCK_DIR="/var/lock/apache2",APACHE_PID_FILE="/var/run/apache2.pid",APACHE_RUN_USER="www-data",APACHE_RUN_GROUP="www-data",APACHE_RUN_DIR="/var/run/apache2"
command = /usr/sbin/apache2 -DFOREGROUND
user = root
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = ${LOG_DIR}/supervisor/supervisord.log
EOF
