#!/bin/bash

if ! id ${APP_USER} &>/dev/null; then

	# create user
	useradd --create-home --home-dir /home/${APP_USER} --shell /bin/bash ${APP_USER}

	# create .my.cnf
	cat >/home/${APP_USER}/.my.cnf <<EOF
[client]
user=root
EOF

	# set environment variables
	cat >>/home/${APP_USER}/.profile <<EOF
export PHP_IDE_CONFIG="serverName=localhost"
export XDEBUG_CONFIG="idekey=phpstorm"
export LANG=de_DE.UTF-8
export LANGUAGE=de_DE.UTF-8
export LC_ALL=de_DE.UTF-8
EOF

fi;

