#!/bin/bash

# set mail host
if [ "${SMTP_PORT_25_TCP_ADDR}" != "" ]; then
    echo ${SMTP_NAME} | awk -F/ '{ print $2 }' > /etc/mailname
    echo "${SMTP_PORT_25_TCP_ADDR} smtp --port ${SMTP_PORT_25_TCP_PORT}" >/etc/nullmailer/remotes

    cat > /etc/supervisor/conf.d/nullmailer.conf <<EOF
[program:nullmailer]
priority = 20
directory = /tmp
command = /usr/sbin/nullmailer-send
user = mail
autostart = true
autorestart = true
stdout_logfile = ${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile = ${LOG_DIR}/supervisor/%(program_name)s.log
EOF

fi;
